Minor updates
RichException: Removed RichException(String msg) 
Load and Save controller: added automati closing for DB access
MainController: fixed bug which caused closing by hitting any key
LoginCredentials: added SQLInjection handling and warning if Username or Password is empty
Util: added warn message. Usage: Util.showAlert("TEST", Alert.AlertType.Warning);
Util: added support for unicode-HEX encoding/decoding
LoadView/SaveView: added close methode